### ISSUE TITLE
Hazus AEBM card 1 progress

### ISSUE THREAD

**Issue by karenng-civicsoftware** [hackoregon/2019-disaster-resilience-data-science#4]
Keep track of the production of AEBM story card 1. Progress was previously documented at [gist](https://gist.github.com/karenng-civicsoftware/a75a67bbd435544da846d14fcf4d1817)

Link to card: [link](http://civicplatform.org/cards/earthquake-damage-estimates-for-buildings-in-tillamook-county)

Link to frontend files: [link](https://github.com/hackoregon/civic/tree/8a318c844992a35a134d1b608b503bf9c699044b/packages/2018-disaster-resilience/src/components/EarthquakeDamageEstimatesForBuildingsInTillamookCounty)

Link to file specifying REST API view: [link](https://github.com/hackoregon/disaster-resilience-backend/blob/22272a79d86712f3db248819741f97dd77bce3ef/api/views.py#L293)

# Team disaster 
Here is a list of tasks to be completed to make sure the suggestions from Jordan, Doug, Ujvala are incorporated into our working demos of our cards.

### modify our data to represent the uncertainty
- [x] upload the `ipynb` files for generating the datasets that would be made available via the REST API calls

## 2. add the data to GitHub
- [x] ask what column names could be accepted properly, the previous column names were not properly concatenated
- [x] use the new API for serving static json

### make REST data API modifications 
- [x] profile PostGIS database and REST API calls to see which part is taking 40s - issue submitted [here](https://github.com/hackoregon/civic-devops/issues/279)

- [x] make sure new data set is used by the API by closing https://github.com/hackoregon/disaster-resilience-backend/issues/54 and adopting PR https://github.com/hackoregon/disaster-resilience-backend/pull/55 

- [x]  test that the API calls work https://service.civicpdx.org/disaster-resilience/
- [x] ask the backend team to improve the load time for the REST API call

## 4. modify content in the frontend card files
see [guide] 

### Hazus card 1: Building loss ratio [link to card 1 frontend files](https://github.com/hackoregon/civic/blob/master/packages/2018-disaster-resilience/src/components/EarthquakeDamageEstimatesForBuildingsInTillamookCounty/EarthquakeDamageEstimatesForBuildingsInTillamookCountyVisualization.js)
- [x] restrict a minimum zoom level
- [ ] add mouse-over tooltips. See [issue](https://github.com/hackoregon/civic/issues/1063)
- [ ] add scale bar

### Content checking 
- [x] validate that the words are copied correctly from [google doc 1 link](https://docs.google.com/document/d/1SY33U2VNvVE4jQ5cUd_zbwFKWYl67HRO2d8vCABNy1Q/edit?usp=sharing) to [the card](http://civicplatform.org/cards/earthquake-damage-estimates-for-buildings-in-tillamook-county)
